---
AWSTemplateFormatVersion: 2010-09-09
Description: |
  Run Rennovate with AWS CodeBuild.

Parameters:
  RenovateVersion:
    Type: String
    Default: latest

  RenovateFlags:
    Type: String
    Description: Run renovate with flags

  RenovateRepositories:
    Type: String
    Description: Comma separated list of repositories

  RenovateSchedule:
    Type: String
    Description: |
      The schedule or rate (frequency) that determines when the renovate
      will be run
    Default: cron(45 23 ? * 1-5 *)

  RenovatePlatform:
    Type: String
    Default: github
    AllowedValues:
      - github
      - gitlab

  RenovatePlatformToken:
    Type: String
    MinLength: 1
    NoEcho: true

  Image:
    Type: String
    Default: aws/codebuild/nodejs:10.1.0

  ComputerType:
    Type: String
    Default: BUILD_GENERAL1_SMALL

  TimeoutInMinutes:
    Type: Number
    Default: 10

Conditions:
  HasRenovateSchedule: {"Fn::Not": [{"Fn::Equals": ["", {"Ref": "RenovateSchedule"}]}]}

Mappings:
  PlatformToEnv:
    gitlab:
      Value: "    GITLAB_TOKEN"
    github:
      Value: "    GITHUB_TOKEN"

Resources:
  RenovatePlatformTokenParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: /renovate-aws/platform_token
      Value: !Ref RenovatePlatformToken

  RenovateRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-ssm
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:*
        - PolicyName: !Sub ${AWS::StackName}-cloudwatch
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/Renovate-*"

  RenovateCronRuleRole:
    Type: AWS::IAM::Role
    Condition: HasRenovateSchedule
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-cron-rule
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                Resource: !Sub arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/Renovate-*

  RenovateCronRule:
    Type: AWS::Events::Rule
    Condition: HasRenovateSchedule
    Properties:
      ScheduleExpression: !Ref RenovateSchedule
      Targets:
        - Id: renovate-cron
          Arn: !GetAtt Renovate.Arn
          Input: "{}"
          RoleArn: !GetAtt RenovateCronRuleRole.Arn

  Renovate:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: !Ref RenovateRole
      Description: Run Renovate
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: !Ref ComputerType
        Image: !Ref Image
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: RENOVATE_VERSION
            Value: !Ref RenovateVersion
          - Name: RENOVATE_REPOSITORIES
            Value: !Sub " ${RenovateRepositories}"
          - Name: RENOVATE_FLAGS
            Value: !Sub " ${RenovateFlags}"
          - Name: RENOVATE_PLATFORM
            Value: !Ref RenovatePlatform
      Source:
        Type: NO_SOURCE
        BuildSpec: !Join
          - ""
          -
            - |
                version: 0.2
                env:
                  variables:
                    CI: "1"
                  parameter-store:
            - !Join
              - ""
              -
                - !Join
                  - ": "
                  -
                    - !FindInMap [ PlatformToEnv, !Ref "RenovatePlatform", Value ]
                    - /renovate-aws/platform_token
                - "\n"
            - |
                phases:
                  install:
                    commands:
                      - npm install renovate@${RENOVATE_VERSION}
                      - "$(npm bin)/renovate --version"
                  build:
                    commands:
                      - $(npm bin)/renovate ${RENOVATE_FLAGS}
      TimeoutInMinutes: !Ref TimeoutInMinutes

Outputs:
  Renovate:
    Value: !Ref Renovate

  RenovateUrl:
    Value: !Sub https://${AWS::Region}.console.aws.amazon.com/codebuild/home?region=${AWS::Region}#/projects/${Renovate}/view
