---
AWSTemplateFormatVersion: 2010-09-09
Description: |
  AWS resources for Renovate

Parameters:
  RenovateVersion:
    Type: String
    Default: latest

  RenovateFlags:
    Type: String
    Description: Run renovate with flags

  RenovateRepositories:
    Type: String
    Description: Comma separated list of repositories

  RenovatePlatform:
    Type: String
    Default: github
    AllowedValues:
      - github
      - gitlab

  RenovateConfigLocation:
    Type: String
    Default: renovate-aws/config/latest/config.zip

  Image:
    Type: String
    Default: aws/codebuild/nodejs:10.1.0

  ComputerType:
    Type: String
    Default: BUILD_GENERAL1_SMALL

  BuildSpec:
    Type: String
    Default: buildspec.yml

  TimeoutInMinutes:
    Type: Number
    Default: 10

  GitHubToken:
    Type: String
    Default: NOT_SET
    MinLength: 1
    NoEcho: true

  GitLabToken:
    Description: |
    Type: String
    Default: NOT_SET
    MinLength: 1
    NoEcho: true

Resources:
  RenovateGitHubToken:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: /renovate-aws/GITHUB_TOKEN
      Value: !Ref GitHubToken

  RenovateGitLabToken:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: /renovate-aws/GITLAB_TOKEN
      Value: !Ref GitLabToken

  RenovateRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-ssm
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:*

        - PolicyName: !Sub ${AWS::StackName}-cloudwatch
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${AWS::StackName}:*"

  Renovate:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}
      ServiceRole: !Ref RenovateRole
      Description: Run Renovate
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: !Ref ComputerType
        Image: !Ref Image
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: RENOVATE_VERSION
            Value: !Ref RenovateVersion
          - Name: RENOVATE_REPOSITORIES
            Value: !Ref RenovateRepositories
          - Name: RENOVATE_FLAGS
            Value: !Ref RenovateFlags
          - Name: RENOVATE_PLATFORM
            Value: !Ref RenovatePlatform
      Source:
        Location: !Ref RenovateConfigLocation
        Type: S3
        BuildSpec: !Ref BuildSpec
      TimeoutInMinutes: !Ref TimeoutInMinutes

